In [2]:
from langchain_community.document_loaders import TextLoader
from langchain_text_splitters import CharacterTextSplitter
from langchain_chroma import Chroma
from langchain_huggingface import HuggingFaceEmbeddings

In [3]:
from dotenv import load_dotenv

load_dotenv()

True

In [4]:
import pandas as pd

books = pd.read_csv("./books_cleaned.csv")

In [5]:
books["tagged_description"].head()

0    9780002005883 A NOVEL THAT READERS and critics...
1    9780002261982 A new 'Christie for Christmas' -...
2    9780006178736 A memorable, mesmerizing heroine...
3    9780006280897 Lewis' work on the nature of lov...
4    9780006280934 "In The Problem of Pain, C.S. Le...
Name: tagged_description, dtype: object

In [5]:
books["tagged_description"].to_csv("./tagged_description.txt",
                                   index = False,
                                   header = False)

In [6]:
raw_documents = TextLoader("./tagged_description.txt", encoding="utf-8").load()
text_splitter = CharacterTextSplitter(chunk_size=1, chunk_overlap=0, separator="\n")

documents = text_splitter.split_documents(raw_documents)

Created a chunk of size 1170, which is longer than the specified 1
Created a chunk of size 1216, which is longer than the specified 1
Created a chunk of size 375, which is longer than the specified 1
Created a chunk of size 311, which is longer than the specified 1
Created a chunk of size 483, which is longer than the specified 1
Created a chunk of size 484, which is longer than the specified 1
Created a chunk of size 962, which is longer than the specified 1
Created a chunk of size 188, which is longer than the specified 1
Created a chunk of size 845, which is longer than the specified 1

Created a chunk of size 296, which is longer than the specified 1
Created a chunk of size 197, which is longer than the specified 1
Created a chunk of size 881, which is longer than the specified 1
Created a chunk of size 1090, which is longer than the specified 1
Created a chunk of size 1191, which is longer than the specified 1
Created a chunk of size 306, which is longer than the specified 1
Created a chunk of size 270, which is longer than the specified 1
Created a chunk of size 213, which is longer than the specified 1
Created a chunk of size 216, which is longer than the specified 1
Created a chunk of size 515, which is longer than the specified 1
Created a chunk of size 754, which is longer than the specified 1
Created a chunk of size 390, which is longer than the specified 1
Created a chunk of size 265, which is longer than the specified 1
Created a chunk of size 253, which is longer than the specified 1
Created a chunk of size 308, which is longer than the specified 1
Created a chunk of size 730, which is longer than the specified 1
Created a chunk of size 723, which is longer than the specified 1
Created a chunk of size 258, which is longer than the specified 1
Created a chunk of size 475, which is longer than the specified 1
Created a chunk of size 272, which is longer than the specified 1
Created a chunk of size 1267, which is longer than the specified 1
Created a chunk of size 683, which is longer than the specified 1
Created a chunk of size 243, which is longer than the specified 1
Created a chunk of size 555, which is longer than the specified 1
Created a chunk of size 523, which is longer than the specified 1
Created a chunk of size 282, which is longer than the specified 1
Created a chunk of size 789, which is longer than the specified 1
Created a chunk of size 566, which is longer than the specified 1
Created a chunk of size 525, which is longer than the specified 1
Created a chunk of size 179, which is longer than the specified 1
Created a chunk of size 299, which is longer than the specified 1
Created a chunk of size 535, which is longer than the specified 1
Created a chunk of size 559, which is longer than the specified 1
Created a chunk of size 565, which is longer than the specified 1
Created a chunk of size 385, which is longer than the specified 1
Created a chunk of size 412, which is longer than the specified 1
Created a chunk of size 463, which is longer than the specified 1
Created a chunk of size 597, which is longer than the specified 1
Created a chunk of size 478, which is longer than the specified 1
Created a chunk of size 461, which is longer than the specified 1
Created a chunk of size 259, which is longer than the specified 1
Created a chunk of size 306, which is longer than the specified 1
Created a chunk of size 616, which is longer than the specified 1
Created a chunk of size 421, which is longer than the specified 1
Created a chunk of size 889, which is longer than the specified 1
Created a chunk of size 695, which is longer than the specified 1
Created a chunk of size 304, which is longer than the specified 1
Created a chunk of size 219, which is longer than the specified 1
Created a chunk of size 277, which is longer than the specified 1
Created a chunk of size 2010, which is longer than the specified 1
Created a chunk of size 175, which is longer than the specified 1
Created a chunk of size 481, which is longer than the specified 1
Created a chunk of size 302, which is longer than the specified 1
Created a chunk of size 522, which is longer than the specified 1
Created a chunk of size 649, which is longer than the specified 1
Created a chunk of size 778, which is longer than the specified 1
Created a chunk of size 165, which is longer than the specified 1
Created a chunk of size 688, which is longer than the specified 1
Created a chunk of size 550, which is longer than the specified 1
Created a chunk of size 1225, which is longer than the specified 1
Created a chunk of size 408, which is longer than the specified 1
Created a chunk of size 1186, which is longer than the specified 1
Created a chunk of size 1216, which is longer than the specified 1
Created a chunk of size 1193, which is longer than the specified 1
Created a chunk of size 1059, which is longer than the specified 1
Created a chunk of size 246, which is longer than the specified 1
Created a chunk of size 690, which is longer than the specified 1
Created a chunk of size 878, which is longer than the specified 1
Created a chunk of size 286, which is longer than the specified 1
Created a chunk of size 768, which is longer than the specified 1
Created a chunk of size 389, which is longer than the specified 1
Created a chunk of size 419, which is longer than the specified 1
Created a chunk of size 210, which is longer than the specified 1
Created a chunk of size 209, which is longer than the specified 1
Created a chunk of size 725, which is longer than the specified 1
Created a chunk of size 209, which is longer than the specified 1
Created a chunk of size 163, which is longer than the specified 1
Created a chunk of size 528, which is longer than the specified 1
Created a chunk of size 523, which is longer than the specified 1
Created a chunk of size 214, which is longer than the specified 1
Created a chunk of size 340, which is longer than the specified 1
Created a chunk of size 901, which is longer than the specified 1
Created a chunk of size 1272, which is longer than the specified 1
Created a chunk of size 560, which is longer than the specified 1
Created a chunk of size 1637, which is longer than the specified 1
Created a chunk of size 438, which is longer than the specified 1
Created a chunk of size 251, which is longer than the specified 1
Created a chunk of size 779, which is longer than the specified 1
Created a chunk of size 718, which is longer than the specified 1
Created a chunk of size 516, which is longer than the specified 1
Created a chunk of size 960, which is longer than the specified 1
Created a chunk of size 200, which is longer than the specified 1
Created a chunk of size 1132, which is longer than the specified 1
Created a chunk of size 170, which is longer than the specified 1
Created a chunk of size 1325, which is longer than the specified 1
Created a chunk of size 853, which is longer than the specified 1
Created a chunk of size 272, which is longer than the specified 1
Created a chunk of size 801, which is longer than the specified 1
Created a chunk of size 1121, which is longer than the specified 1
Created a chunk of size 838, which is longer than the specified 1
Created a chunk of size 262, which is longer than the specified 1
Created a chunk of size 237, which is longer than the specified 1
Created a chunk of size 734, which is longer than the specified 1
Created a chunk of size 1195, which is longer than the specified 1
Created a chunk of size 712, which is longer than the specified 1
Created a chunk of size 775, which is longer than the specified 1
Created a chunk of size 280, which is longer than the specified 1
Created a chunk of size 309, which is longer than the specified 1
Created a chunk of size 358, which is longer than the specified 1
Created a chunk of size 768, which is longer than the specified 1
Created a chunk of size 767, which is longer than the specified 1
Created a chunk of size 718, which is longer than the specified 1
Created a chunk of size 2012, which is longer than the specified 1
Created a chunk of size 308, which is longer than the specified 1
Created a chunk of size 1288, which is longer than the specified 1
Created a chunk of size 1231, which is longer than the specified 1
Created a chunk of size 729, which is longer than the specified 1
Created a chunk of size 750, which is longer than the specified 1
Created a chunk of size 447, which is longer than the specified 1
Created a chunk of size 1242, which is longer than the specified 1
Created a chunk of size 311, which is longer than the specified 1
Created a chunk of size 914, which is longer than the specified 1
Created a chunk of size 306, which is longer than the specified 1
Created a chunk of size 846, which is longer than the specified 1
Created a chunk of size 1128, which is longer than the specified 1
Created a chunk of size 1075, which is longer than the specified 1
Created a chunk of size 1320, which is longer than the specified 1
Created a chunk of size 363, which is longer than the specified 1
Created a chunk of size 2834, which is longer than the specified 1
Created a chunk of size 237, which is longer than the specified 1
Created a chunk of size 242, which is longer than the specified 1
Created a chunk of size 173, which is longer than the specified 1
Created a chunk of size 206, which is longer than the specified 1
Created a chunk of size 572, which is longer than the specified 1
Created a chunk of size 208, which is longer than the specified 1
Created a chunk of size 367, which is longer than the specified 1
Created a chunk of size 1143, which is longer than the specified 1
Created a chunk of size 1006, which is longer than the specified 1
Created a chunk of size 715, which is longer than the specified 1
Created a chunk of size 712, which is longer than the specified 1
Created a chunk of size 2510, which is longer than the specified 1
Created a chunk of size 956, which is longer than the specified 1
Created a chunk of size 309, which is longer than the specified 1
Created a chunk of size 351, which is longer than the specified 1
Created a chunk of size 641, which is longer than the specified 1
Created a chunk of size 405, which is longer than the specified 1
Created a chunk of size 525, which is longer than the specified 1
Created a chunk of size 795, which is longer than the specified 1
Created a chunk of size 167, which is longer than the specified 1
Created a chunk of size 391, which is longer than the specified 1
Created a chunk of size 256, which is longer than the specified 1
Created a chunk of size 1424, which is longer than the specified 1
Created a chunk of size 1085, which is longer than the specified 1
Created a chunk of size 1146, which is longer than the specified 1
Created a chunk of size 1268, which is longer than the specified 1
Created a chunk of size 790, which is longer than the specified 1
Created a chunk of size 297, which is longer than the specified 1
Created a chunk of size 1088, which is longer than the specified 1
Created a chunk of size 874, which is longer than the specified 1
Created a chunk of size 256, which is longer than the specified 1
Created a chunk of size 876, which is longer than the specified 1
Created a chunk of size 808, which is longer than the specified 1
Created a chunk of size 1814, which is longer than the specified 1
Created a chunk of size 1830, which is longer than the specified 1
Created a chunk of size 1064, which is longer than the specified 1
Created a chunk of size 955, which is longer than the specified 1
Created a chunk of size 1182, which is longer than the specified 1
Created a chunk of size 283, which is longer than the specified 1
Created a chunk of size 283, which is longer than the specified 1
Created a chunk of size 288, which is longer than the specified 1
Created a chunk of size 1286, which is longer than the specified 1
Created a chunk of size 1644, which is longer than the specified 1
Created a chunk of size 759, which is longer than the specified 1
Created a chunk of size 1932, which is longer than the specified 1
Created a chunk of size 874, which is longer than the specified 1
Created a chunk of size 2008, which is longer than the specified 1
Created a chunk of size 2285, which is longer than the specified 1
Created a chunk of size 173, which is longer than the specified 1
Created a chunk of size 1003, which is longer than the specified 1
Created a chunk of size 579, which is longer than the specified 1
Created a chunk of size 290, which is longer than the specified 1
Created a chunk of size 255, which is longer than the specified 1
Created a chunk of size 1144, which is longer than the specified 1
Created a chunk of size 559, which is longer than the specified 1
Created a chunk of size 1143, which is longer than the specified 1
Created a chunk of size 245, which is longer than the specified 1
Created a chunk of size 1088, which is longer than the specified 1
Created a chunk of size 1483, which is longer than the specified 1
Created a chunk of size 223, which is longer than the specified 1
Created a chunk of size 1137, which is longer than the specified 1
Created a chunk of size 724, which is longer than the specified 1
Created a chunk of size 668, which is longer than the specified 1
Created a chunk of size 767, which is longer than the specified 1
Created a chunk of size 608, which is longer than the specified 1
Created a chunk of size 572, which is longer than the specified 1
Created a chunk of size 967, which is longer than the specified 1
Created a chunk of size 859, which is longer than the specified 1
Created a chunk of size 1034, which is longer than the specified 1
Created a chunk of size 191, which is longer than the specified 1
Created a chunk of size 367, which is longer than the specified 1
Created a chunk of size 497, which is longer than the specified 1
Created a chunk of size 652, which is longer than the specified 1
Created a chunk of size 350, which is longer than the specified 1
Created a chunk of size 735, which is longer than the specified 1
Created a chunk of size 527, which is longer than the specified 1
Created a chunk of size 1017, which is longer than the specified 1
Created a chunk of size 972, which is longer than the specified 1
Created a chunk of size 206, which is longer than the specified 1
Created a chunk of size 690, which is longer than the specified 1
Created a chunk of size 546, which is longer than the specified 1
Created a chunk of size 244, which is longer than the specified 1
Created a chunk of size 209, which is longer than the specified 1
Created a chunk of size 378, which is longer than the specified 1
Created a chunk of size 933, which is longer than the specified 1
Created a chunk of size 564, which is longer than the specified 1
Created a chunk of size 856, which is longer than the specified 1
Created a chunk of size 717, which is longer than the specified 1
Created a chunk of size 749, which is longer than the specified 1
Created a chunk of size 714, which is longer than the specified 1
Created a chunk of size 326, which is longer than the specified 1
Created a chunk of size 243, which is longer than the specified 1
Created a chunk of size 1090, which is longer than the specified 1
Created a chunk of size 725, which is longer than the specified 1
Created a chunk of size 247, which is longer than the specified 1
Created a chunk of size 229, which is longer than the specified 1
Created a chunk of size 706, which is longer than the specified 1
Created a chunk of size 1914, which is longer than the specified 1
Created a chunk of size 397, which is longer than the specified 1
Created a chunk of size 487, which is longer than the specified 1
Created a chunk of size 622, which is longer than the specified 1
Created a chunk of size 561, which is longer than the specified 1
Created a chunk of size 558, which is longer than the specified 1
Created a chunk of size 388, which is longer than the specified 1
Created a chunk of size 231, which is longer than the specified 1
Created a chunk of size 427, which is longer than the specified 1
Created a chunk of size 418, which is longer than the specified 1
Created a chunk of size 284, which is longer than the specified 1
Created a chunk of size 168, which is longer than the specified 1
Created a chunk of size 626, which is longer than the specified 1
Created a chunk of size 2616, which is longer than the specified 1
Created a chunk of size 1580, which is longer than the specified 1
Created a chunk of size 391, which is longer than the specified 1
Created a chunk of size 996, which is longer than the specified 1
Created a chunk of size 849, which is longer than the specified 1
Created a chunk of size 265, which is longer than the specified 1
Created a chunk of size 338, which is longer than the specified 1
Created a chunk of size 1530, which is longer than the specified 1
Created a chunk of size 215, which is longer than the specified 1
Created a chunk of size 291, which is longer than the specified 1
Created a chunk of size 2032, which is longer than the specified 1
Created a chunk of size 398, which is longer than the specified 1
Created a chunk of size 1619, which is longer than the specified 1
Created a chunk of size 700, which is longer than the specified 1
Created a chunk of size 824, which is longer than the specified 1
Created a chunk of size 356, which is longer than the specified 1
Created a chunk of size 843, which is longer than the specified 1
Created a chunk of size 1191, which is longer than the specified 1
Created a chunk of size 197, which is longer than the specified 1
Created a chunk of size 510, which is longer than the specified 1
Created a chunk of size 665, which is longer than the specified 1
Created a chunk of size 1284, which is longer than the specified 1
Created a chunk of size 262, which is longer than the specified 1
Created a chunk of size 244, which is longer than the specified 1
Created a chunk of size 217, which is longer than the specified 1
Created a chunk of size 200, which is longer than the specified 1
Created a chunk of size 1268, which is longer than the specified 1
Created a chunk of size 1277, which is longer than the specified 1
Created a chunk of size 200, which is longer than the specified 1
Created a chunk of size 1058, which is longer than the specified 1
Created a chunk of size 380, which is longer than the specified 1
Created a chunk of size 271, which is longer than the specified 1
Created a chunk of size 179, which is longer than the specified 1
Created a chunk of size 227, which is longer than the specified 1
Created a chunk of size 224, which is longer than the specified 1
Created a chunk of size 784, which is longer than the specified 1
Created a chunk of size 971, which is longer than the specified 1
Created a chunk of size 615, which is longer than the specified 1
Created a chunk of size 165, which is longer than the specified 1
Created a chunk of size 759, which is longer than the specified 1
Created a chunk of size 291, which is longer than the specified 1
Created a chunk of size 247, which is longer than the specified 1
Created a chunk of size 965, which is longer than the specified 1
Created a chunk of size 234, which is longer than the specified 1
Created a chunk of size 845, which is longer than the specified 1
Created a chunk of size 788, which is longer than the specified 1
Created a chunk of size 650, which is longer than the specified 1
Created a chunk of size 986, which is longer than the specified 1
Created a chunk of size 799, which is longer than the specified 1
Created a chunk of size 193, which is longer than the specified 1
Created a chunk of size 1163, which is longer than the specified 1
Created a chunk of size 255, which is longer than the specified 1
Created a chunk of size 203, which is longer than the specified 1
Created a chunk of size 1058, which is longer than the specified 1
Created a chunk of size 248, which is longer than the specified 1
Created a chunk of size 877, which is longer than the specified 1
Created a chunk of size 819, which is longer than the specified 1
Created a chunk of size 380, which is longer than the specified 1
Created a chunk of size 757, which is longer than the specified 1
Created a chunk of size 571, which is longer than the specified 1
Created a chunk of size 628, which is longer than the specified 1
Created a chunk of size 868, which is longer than the specified 1
Created a chunk of size 622, which is longer than the specified 1

In [7]:
documents[0].page_content

'"9780002005883 A NOVEL THAT READERS and critics have been eagerly anticipating for over a decade, Gilead is an astonishingly imagined story of remarkable lives. John Ames is a preacher, the son of a preacher and the grandson (both maternal and paternal) of preachers. It’s 1956 in Gilead, Iowa, towards the end of the Reverend Ames’s life, and he is absorbed in recording his family’s story, a legacy for the young son he will never see grow up. Haunted by his grandfather’s presence, John tells of the rift between his grandfather and his father: the elder, an angry visionary who fought for the abolitionist cause, and his son, an ardent pacifist. He is troubled, too, by his prodigal namesake, Jack (John Ames) Boughton, his best friend’s lost son who returns to Gilead searching for forgiveness and redemption. Told in John Ames’s joyous, rambling voice that finds beauty, humour and truth in the smallest of life’s details, Gilead is a song of celebration and acceptance of the best and the worst the world has to offer. At its heart is a tale of the sacred bonds between fathers and sons, pitch-perfect in style and story, set to dazzle critics and readers alike."'

In [8]:
# Using a free langchain embedding instead of OpenAI paid service
embeddings = HuggingFaceEmbeddings(model_name='all-MiniLM-l6-v2')


db_books = Chroma.from_documents(
    documents,
    embedding=embeddings
)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-l6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [48]:
query = "A book teaching young adults on about health"

docs = db_books.similarity_search(query, k = 5)

docs_isbn13 = [ int(doc.page_content.strip('"').split()[0]) for doc in docs ]
docs_isbn13

relevant_books = books[books.isbn13.isin(docs_isbn13)]
relevant_books[['isbn13', 'description']]

,isbn13,description
1652,9780374528539,"A lighthearted but insightful guide to raising adolescent children shows parents how to deal with teenagers living in a faster-paced, less morally certain world than the one they knew. Original. 50,000 first printing."
2925,9780618479030,"The best-selling books of Andrew Weil, ""the guru of alternative medicine,"" (San Francisco Examiner) offer a comprehensive blend of traditional and alternative methods that help to achieve better health in the modern world. Natural Health, Natural Medicine is a comprehensive resource for everything you need to know to maintain optimum health and treat common ailments. This landmark book incorporates Dr. Weil’s theories of preventive health maintenance and alternative healing into one extremely useful and readable reference, featuring general diet and nutrition information as well as simple recipes, answers to readers’ most pressing questions, a catalogue of home remedies, invaluable resources, and hundreds of practical tips. This edition includes up-to-the-minute scientific findings and has been expanded to provide trustworthy advice about low-carb diets, hormone replacement therapy, Alzheimer’s, attention deficit disorder, reflux disease, autism, type 2 diabetes, erectile dysfunction, the flu, and much more."
4252,9780936197449,"A survival guide for parents helps beleagured adults navigate their childrens' teen years, with advice on how to turn adolescents into strong, confident, productive adults."
4421,9781401211349,"Presents a practical guide that addresses many of the tough issues teens and parents face, and offers advice to maintaining a positive dialogue that fostered mutual respect."
4713,9781576839546,"Cline and Fay offer advice to help parents raise kids who are self-confident, motivated, and ready for the world by teaching them responsibility and the logic of life, thereby giving them the opportunity to solve their own problems from the earliest possible age."

In [49]:
def retrieve_semantic_recommendation(
        query: str,
        top_k: int = 8
) -> pd.DataFrame:
    recs = db_books.similarity_search(query, k=top_k)

    books_list = []
    for i in range(len(recs)):
        books_list.append(int(recs[i].page_content.strip('"').split()[0]))
    
    return books_list

In [50]:
retrieved_isbn13 = retrieve_semantic_recommendation("Science and Technology", top_k=3)

relevant_books = books[books.isbn13.isin(retrieved_isbn13)]
relevant_books[['isbn13', 'description']]

,isbn13,description
2887,9780618056736,"Offers an assessment of what science is, how it feeds the human appetite for wonder, and how ""unweaving"" the mysteries of science can be even more beautiful than the mystery itself."
3247,9780713998788,"The explosion of advanced technologies, knowledge pools and resources that have connected over the planet levelling the playing field as never before, each of us is potentially an equal and competitor of the other."
3835,9780802713520,"Generations have grown up knowing that the equation E=mc2 changed the shape of our world, but never understanding what it actually means, why it was so significant, and how it informs our daily lives today—governing, as it does, everything from the atomic bomb to a television's cathode ray tube to the carbon dating of prehistoric paintings. In this book, David Bodanis writes the ""biography"" of one of the greatest scientific discoveries in history—that the realms of energy and matter are inescapably linked—and, through his skill as a writer and teacher, he turns a seemingly impenetrable theory into a dramatic human achievement and an uncommonly good story."

In [51]:
books['categories'].value_counts().reset_index()

                     categories  count
0                       Fiction   2111
1              Juvenile Fiction    390
2     Biography & Autobiography    311
3                       History    207
4            Literary Criticism    124
..                          ...    ...
474                  Aged women      1
475                 Imperialism      1
476  Human-animal relationships      1
477                       Amish      1
478               Human cloning      1

[479 rows x 2 columns]

In [52]:
books['categories'].value_counts().reset_index().query('count > 50')

                   categories  count
0                     Fiction   2111
1            Juvenile Fiction    390
2   Biography & Autobiography    311
3                     History    207
4          Literary Criticism    124
5                    Religion    117
6                  Philosophy    117
7     Comics & Graphic Novels    116
8                       Drama     86
9         Juvenile Nonfiction     57
10                    Science     56
11                     Poetry     51

In [59]:
category_mapping = {
    'Fiction': 'Fiction',
    'Juveline Fiction': "Children's Fiction",
    'Biography & Autobiography': 'Nonfiction',
    'History': 'Nonfiction',
    'Literary Criticism': 'Nonfiction',
    'Philosophy': 'Nonfiction',
    'Religion': 'Nonfiction',
    'Comics & Graphic Novels': 'Fiction',
    'Drama': 'Fiction',
    'Juveline Nonfiction': "Children's Nonfiction",
    'Science': 'Nonfiction',
    'Poetry': 'Fiction'
}

In [61]:
books['simple_categories'] = books['categories'].map(category_mapping)

In [64]:
books[~(books['simple_categories'].isna())]

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,tagged_description,simple_categories
0,9780002005883,0002005883,Gilead,Marilynne Robinson,Fiction,http://books.google.com/books/content?id=KQZCPgAACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api,"A NOVEL THAT READERS and critics have been eagerly anticipating for over a decade, Gilead is an astonishingly imagined story of remarkable lives. John Ames is a preacher, the son of a preacher and the grandson (both maternal and paternal) of preachers. It’s 1956 in Gilead, Iowa, towards the end of the Reverend Ames’s life, and he is absorbed in recording his family’s story, a legacy for the young son he will never see grow up. Haunted by his grandfather’s presence, John tells of the rift between his grandfather and his father: the elder, an angry visionary who fought for the abolitionist cause, and his son, an ardent pacifist. He is troubled, too, by his prodigal namesake, Jack (John Ames) Boughton, his best friend’s lost son who returns to Gilead searching for forgiveness and redemption. Told in John Ames’s joyous, rambling voice that finds beauty, humour and truth in the smallest of life’s details, Gilead is a song of celebration and acceptance of the best and the worst the world has to offer. At its heart is a tale of the sacred bonds between fathers and sons, pitch-perfect in style and story, set to dazzle critics and readers alike.",2004.0,3.85,247.0,361.0,Gilead,"9780002005883 A NOVEL THAT READERS and critics have been eagerly anticipating for over a decade, Gilead is an astonishingly imagined story of remarkable lives. John Ames is a preacher, the son of a preacher and the grandson (both maternal and paternal) of preachers. It’s 1956 in Gilead, Iowa, towards the end of the Reverend Ames’s life, and he is absorbed in recording his family’s story, a legacy for the young son he will never see grow up. Haunted by his grandfather’s presence, John tells of the rift between his grandfather and his father: the elder, an angry visionary who fought for the abolitionist cause, and his son, an ardent pacifist. He is troubled, too, by his prodigal namesake, Jack (John Ames) Boughton, his best friend’s lost son who returns to Gilead searching for forgiveness and redemption. Told in John Ames’s joyous, rambling voice that finds beauty, humour and truth in the smallest of life’s details, Gilead is a song of celebration and acceptance of the best and the worst the world has to offer. At its heart is a tale of the sacred bonds between fathers and sons, pitch-perfect in style and story, set to dazzle critics and readers alike.",Fiction
2,9780006178736,0006178731,Rage of angels,Sidney Sheldon,Fiction,http://books.google.com/books/content?id=FKo2TgANz74C&printsec=frontcover&img=1&zoom=1&source=gbs_api,"A memorable, mesmerizing heroine Jennifer -- brilliant, beautiful, an attorney on the way up until the Mafia's schemes win her the hatred of an implacable enemy -- and a love more destructive than hate. A dangerous, dramatic world The Dark Arena of organized crime and flashbulb lit courtrooms where ambitious prosecutors begin their climb to political power.",1993.0,3.93,512.0,29532.0,Rage of angels,"9780006178736 A memorable, mesmerizing heroine Jennifer -- brilliant, beautiful, an attorney on the way up until the Mafia's schemes win her the hatred of an implacable enemy -- and a love more destructive than hate. A dangerous, dramatic world The Dark Arena of organized crime and flashbulb lit courtrooms where ambitious prosecutors begin their climb to political power.",Fiction
8,9780006482079,0006482074,Warhost of Vastmark,Janny Wurts,Fiction,http://books.google.com/books/content?id=uOL0fpS9WZkC&printsec=frontcover&img=1&zoom=1&source=gbs_api,"Tricked once more by his wily half-brother, Lysaer, Lord of Light, arrives at the tiny harbor town of Merior to find that Arithon's ship yards have been abandoned and meticulously destroyed, and that the Master of Shadow has disappeared as if into thin air. Meanwhile Arithon and the Mad Prophet Dakar are traveling on foot through the treacherous Kelhorn Mountains towards the Vastmark clans, there to raise further support for his cause. But raising a warhost is a costly business. Is it mere coincidence that Princess Talith—Lysaer's beautiful, headstrong wife—is taken captive and held for a vast ransom by a master brigand? The forces of light and shadow circle and feint, drawing ever closer to a huge conflict. And in the background the Fellowship of Seven Sorcerers and the Koriani Enchantresses watch and plan, and wait.",1995.0,4.03,522.0,2966.0,Warhost of Vastmark,"9780006482079 Tricked once more by his wily half-brother, Lysaer, Lord of Light, arrives at the tiny harbor town of Merior to find that Arithon's ship yards have been abandoned and meticulously destroyed, and that the Master of Shadow has disappeared as if into thin air. Meanwhile Arithon and the Mad Prophet Dakar are traveling on foot through the treacherous Kelhorn Mountains towards the Vastmark clans, there to raise further support for his cause. But raising a warhost is a costly business. Is it mere coincidence that Princess Talith—Lysaer's beautiful, headstrong wife—is taken captive and held for a vast ransom by a master brigand? The forces of light and shadow circle and feint, drawing ever closer to a huge conflict. And in the background the Fellowship of Seven Sorcerers and the Koriani Enchantresses watch and plan, and wait.",Fiction
46,9780007121014,0007121016,Taken at the Flood,Agatha Christie,Fiction,http://books.google.com/books/content?id=3gWlxIFlMEwC&printsec=frontcover&img=1&zoom=1&source=gbs_api,"A Few Weeks After Marrying An Attractive Young Widow, Gordon Cloade Is Tragically Killed By A Bomb Blast In The London Blitz. Overnight, The Former Mrs Underhay Finds Herself In Sole Possession Of The Cloade Family Fortune. Shortly Afterwards, Hercule Poirot Receives A Visit From The Dead Man S Sister-In-Law Who Claims She Has Been Warned By Spirits That Mrs Underhay S First Husband Is Still Alive. Poirot Has His Suspicions When He Is Asked To Find A Missing Person Guided Only By The Spirit World. Yet What Mystifies Poirot Most Is The Woman S True Motive For Approaching Him&",2002.0,3.71,352.0,8852.0,Taken at the Flood,"9780007121014 A Few Weeks After Marrying An Attractive Young Widow, Gordon Cloade Is Tragically Killed By A Bomb Blast In The London Blitz. Overnight, The Former Mrs Underhay Finds Herself In Sole Possession Of The Cloade Family Fortune. Shortly Afterwards, Hercule Poirot Receives A Visit From The Dead Man S Sister-In-Law Who Claims She Has Been Warned By Spirits That Mrs Underhay S First Husband Is Still Alive. Poirot Has His Suspicions When He Is Asked To Find A Missing Person Guided Only By The Spirit World. Yet What Mystifies Poirot Most Is The Woman S True Motive For Approaching Him&",Fiction
58,9780007149827,0007149824,The Yiddish Policemen's Union,Michael Chabon,Fiction,http://books.google.com/books/content?id=-reD1g77BfsC&printsec=frontcover&img=1&zoom=1&source=gbs_api,"For sixty years, Jewish refugees and their descendants have prospered in the Federal District of Sitka, a ""temporary"" safe haven created in the wake of revelations of the Holocaust and the shocking 1948 collapse of the fledgling state of Israel. Proud, grateful, and longing to be American, the Jews of the Sitka District have created their own little world in the Alaskan panhandle, a vibrant, gritty, soulful, and complex frontier city that moves to the music of Yiddish. For sixty years they have been left alone, neglected and half-forgotten in a backwater of history. Now the District is set to revert to Alaskan control, and their dream is coming to an end: once again the tides of history threaten to sweep them up and carry them off into the unknown. But homicide detective Meyer Landsman of the District Police has enough problems without worrying about the upcoming Reversion. His life is a shambles, his marriage a wreck, his career a disaster. He and his half-Tlingit partner, Berko Shemets, can't catch a break in any of their outstanding cases. Landsman's new supervisor is the love of his life—and also his worst nightmare. And in the cheap hotel where he has washed up, someone has just committed a murder—right under Landsman's nose. Out of habit, obligation, and a mysterious sense that it somehow offers him a shot at redeeming himself, Landsman begins to investigate the killing of his neighbor, a former chess prodigy. But when word comes down from on high that the case is to be dropped immediately, Landsman soon finds himself contending with all the powerful forces of faith, obsession, hopefulness, evil, and salvation that are his heritage—and with the unfinished business of his marriage to Bina Gelbfish, the one person who understands his darkest fears. At once a gripping whodunit, a love story, an homage to 1940s noir, and an exploration of the mysteries of exile and redemption, The Yiddish Policemen's Union is a novel only Michael Chabon could have written.",2007.0,3.70,414.0,51219.0,The Yiddish Policemen's Union: A Novel,"9780007149827 For sixty years, Jewish refugees and their descendants have prospered in the Federal District of Sitka, a ""temporary"" safe haven created in the wake of revelations of the Holocaust and the shocking 1948 collapse of the fledgling state of Israel. Proud, grateful, and longing to be American, the Jews of the Sitka District have created their own little world in the Alaskan panhandle, a vibrant, gritty, soulful, and complex frontier city that moves to the music of Yiddish. For sixty years they have been left alone, neglected and half-forgotten in a backwater of history. Now the District is set to revert to Alaskan control, and their dream is coming to an end: once again the tides of history threaten to sweep them up and carry them off into the unknown. But homicide detective Meyer Landsman of the District Police has enough problems without worrying about the upcoming Reversion. His life is a shambles, his marriage a wreck, his career a disaster. He and his half-Tlingit partner, Berko Shemets, can't catch a break in any of their outstanding cases. Landsman's new supervisor is the love of his life—and also his worst nightmare. And in the cheap hotel where he has washed up, someone has just committed a murder—right under Landsman's nose. Out of habit, obligation, and a mysterious sense that it somehow offers him a shot at redeeming himself, Landsman begins to investigate the killing of his neighbor, a former chess prodigy. But when word comes down from on high that the case is to be dropped immediately, Landsman soon finds himself contending with all the powerful forces of faith, obsession, hopefulness, evil, and salvation that are his heritage—and with the unfinished business of his marriage to Bina Gelbfish, the one person who understands his darkest fears. At once a gripping whodunit, a love story, an homage to 1940s noir, and an exploration of the mysteries of exile and redemption, The Yiddish Policemen's Union is a novel only Michael Chabon could have written.",Fiction
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5178,9781933648279,1933648279,Night Has a Thousand Eyes,Cornell Woolrich,Fiction,http://books.google.com/books/content?id=3Gk6swEACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api,"""Cornell Woolrich's novels define the essence of noir nihilism.""-Marilyn Stasio, The New York Times Book Review One of Woolrich's most famous novels, this classic noir tale of a con man struggling with his ability to see the future is arguably the author's best in its depiction of his vision of doomed predestination. From the 1930s until his death in 1968, Cornell Woolrich riveted the reading public with his unparalleled suspense stories. Classic films like Alfred Hitchcock's Rear Window and novels such as Rendezvous in Black earned Woolrich epithets like ""the twentieth century's Edgar Allan Poe"" and ""the father of noir.""",2007.0,3.77,344.0,680.0,Night Has a Thousand Eyes,"9781933648279 ""Cornell Woolrich's novels define the essence of noir nihilism.""-Marilyn Stasio, The New York Times Book Review One of Woolrich's most famous novels, this classic noir tale of a con man struggling with his ability to see the future is arguably the author's best in its depiction of his vision of doomed predestination. From the 1930s until his death in 1968, Cornell Woolrich riveted the reading public with his unparalleled suspense stories. Classic films like Alfred Hitchcock's Rear Window and novels such as Rendezvous in Black earned Woolrich epithets like ""the twentieth century's Edgar Allan Poe"" and ""the father of noir.""",Fiction
5188,9784770028969,4770028962,Coin Locker Babies,村上龍,Fiction,http://books.google.com/books/content?id=87DJwAEACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api,"Rescued from the lockers in which they were left to die as infants and raised to freely follow their ambitions, Kiku and Hashi begin parallel quests of vengeance against the mothers that abandoned them and the society that let it happen.",2002.0,3.75,393.0,5560.0,Coin Locker Babies,"9784770028969 Rescued from the lockers in which they were left to die as infants and raised to freely follow their ambitions, Kiku and Hashi begin parallel quests of vengeance against the mothers that abandoned them and the society that let it happen.",Fiction
5189,9788122200850,8122200850,"Cry, the Peacock",Anita Desai,Fiction,http://books.google.com/books/content?id=_QKwVYqp7ugC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api,"This book is the story of a young girl obsessed by a childhood prophecy of disaster. The author builds up an atmosphere of tension and oppression, in the middle of an Indian summer.",1980.0,3.22,218.0,134.0,"Cry, the Peacock","9788122200850 This book is the story of a young girl obsessed by a childhood prophecy of disaster. The author builds up an atmosphere of tension and oppression, in the middle of an Indian summer.",Fiction
5195,9788185300535,8185300534,I Am that,Sri Nisargadatta Maharaj;Sudhakar S. Dikshit,Philosophy,http://books.google.com/books/content?id=Fv_JPQAACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api,"This collection of the timeless teachings of one of the greatest sages of India, is a testament to the uniqueness of the seer's life and work. The book (now in its ninth printing) continues to draw new audiences and to enlighten anxious seekers for self-realisation. Sri Nisargadatta Maharaj was a teacher who did not propound any ideology or religion but gently unwrapped the mystery of the self. His message is simple, direct and yet sublime. The book preserves his dialogues with the followers who came from around the world seeking guidance in destroying false identities. The sage's sole concern was with human suffering and the ending of suffering. It was his mission to guide the individual to an understanding of his true nature and the timelessness of being. He taught that mind must recognise and penetrate its own state of being, not 'being this or that, here or there, then or now', but just timeless being. This is a legacy from a unique teacher who helps the reader to a clearer understanding of himself.",1999.0,4.51,531.0,104.0,I Am that: Talks with Sri Nisargadatta Maharaj,"9788185300535 This collection of the timeless teachings of one of the greatest sages of India, is a testament to the uniqueness of the seer's life and work. The book (now in its ninth printing) continues to draw new audiences and to enlighten anxious seekers for self-realisation. Sri Nisargadatta Maharaj was a teacher who did not propound any ideology or religion but gently unwrapped the mystery of the self. His message is simple, direct and yet sublime. The book preserves his dialogues with the followers who came from around the world seeking guidance in destroying false identities. The sage's sole concern was with human suffering and the ending of suffering. It was his mission to guide the individual to an understanding of his true nature and the timelessness of being. He taught that mind must recognise and penetrate its own state of being, not 'being this or that, here or there, then or now', but just timeless being. This is a legacy from a unique teacher who helps the reader to a clearer understanding of himself.",Nonfiction
5196,9789027712059,9027712050,The Berlin Phenomenology,Georg Wilhelm Friedrich Hegel,History,http://books.google.com/books/content?id=Vy7SkjvmfLMC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api,"Since the three volume edition ofHegel's Philosophy of Subjective Spirit (1978, 19792) has been so well received, I have been encouraged to select that part of it most suitable for teaching purposes, and to publish it here as a separate work. As a teaching text, the Berlin Phenomenology has several important advan­ tages. Unlike so many ofHegel's writings, must notably theJena Phenomeno­ logy of 1807, it is concise and to the point, and concemed with issues already familiar to most students of philosophy. Since it consists for the most part of a searching and radical analysis of Kant's epistemology, Fichte's ethics and Schelling's system-building, it provides tirst-rate insight into Hegel's assessment of his immedi~te predecessors. When considered in context, as part of the Encyclopaedia if the Philosophical Sciences, it enables us to distinguish dearly between the systematic, the logical and the psychological aspects of Hegelianism, and is therefore also relevant to some of the central issues in modem phenomenology. It is to be hoped that the introduction and notes prepared for the present edition will prove helpful to both teachers and students. Every effort has been ma de to produce a thoroughly reliable ba sic text and an accurate translation. The text published in 1978 was prepared at the Hegel Archive in Bochum from photocopies, and I am most grateful to the Central Interfaculty of the Erasmus University, Rotterdam, for having made it possible for me to check the printed version against the original manuscripts.",1981.0,0.00,210.0,0.0,The Berlin Phenomenology,"9789027712059 Since the three volume edition ofHegel's Philosophy of Subjective Spirit (1978, 19792) has been so well received, I have been encouraged to select that part of it most suitable for teaching purposes, and to publish it here as a separate work. As a teaching text, the Berlin Phenomenology has several important advan­ tages. Unlike so many ofHegel's writings, must notably theJena Phenomeno­ logy of 1807, it is concise and to the point, and concemed with issues already familiar to most students of philosophy. Since it consists for the most part of a searching and radical analysis of Kant's epistemology, Fichte's ethics and Schelling's system-building, it provides tirst-rate insight into Hegel's assessment of his immedi~te predecessors. When considered in context, as part of the Encyclopaedia if the Philosophical Sciences, it enables us to distinguish dearly between the systematic, the logical and the psychological aspects of Hegelianism, and is therefore also relevant to some of the central issues in modem phenomenology. It is to be hoped that the introduction and notes prepared for the present edition will prove helpful to both teachers and students. Every effort has been ma de to produce a thoroughly reliable ba sic text and an accurate translation. The text published in 1978 was prepared at the Hegel Archive in Bochum from photocopies, and I am most grateful to the Central Interfaculty of the Erasmus University, Rotterdam, for having made it possible for me to check the printed version against the original manuscripts.",Nonfiction